### ISSUE TITLE
Hearth games client not uploading

### ISSUE THREAD

**Issue by omrianh** [emilic/hearthgamesclient#2]
Hi, 

This client has been so amazing and the website has been crucial to my HS improvement especially in Arena.  Since the last patch to the client, I have been unable to reliably upload my games.  This is the message that appears:

03:27:04 - Started HearthGamesClientApplication in 10.738 seconds (JVM running for 12.925)
12:17:27 - Posting game to the server...
12:17:29 - Server returned error and will not process game. If a valid game was uploaded it will be queued for analysis and reprocessing on the server.
12:17:29 - 400 Bad Request

I've tried restarting both the client and HS with no results.  I've also tried redownloading and reinstalling the client.  Please help!

Thank you so much, and thanks for making such a great website/client.

**Comment by emilic** [comment]
I will look into and fix this tonight.  In the meantime you could manually upload your log files.

**Comment by omrianh** [comment]
Thanks, appreciate it.  Just to let you know, since today I've noticed arena games are uploading.  However, ranked and casual are not.

**Comment by emilic** [comment]
Ok, good to know, If it wasn't for me having a day job I would have already fixed this :)

**Comment by emilic** [comment]
I have updated the server to fix this issue.  It was caused by being too restrictive on what loggers should be contained in the log.  I relaxed the rule a little since not all games have all loggers. 

Let me know if you still have any issues.  This was a quick fix.  I am still working through game detection issues but at least uploading games should be more stable.
